version: ~> 1.0

import:
  - silverstripe/silverstripe-travis-shared:config/provision/self.yml

env:
  global:
    - PHPUNIT_TEST=1
    - DB=MYSQL

jobs:
  include:
    - php: 7.1
      env:
        - PHPUNIT_SUITE="core,cwpcore,admin,cwpcms"
        - PHPCS_TEST=1
    - php: 7.2
      env:
        - PHPUNIT_SUITE="Default,cwpsearch"
        - COW_TEST=1
    - php: 7.3
      env:
        - PHPUNIT_SUITE="admin,cwpcms,Default"
    - php: 7.4
      env:
        - PHPUNIT_SUITE="cwpsearch"
